/* src/config/newsConfig.js */

export const availableCategories = [
    { value: "business", text: "Business" },
    { value: "crime", text: "Crime" },
    { value: "domestic", text: "Domestic" },
    { value: "education", text: "Education" },
    { value: "entertainment", text: "Entertainment" },
    { value: "environment", text: "Environment" },
    { value: "food", text: "Food" },
    { value: "health", text: "Health" },
    { value: "lifestyle", text: "Lifestyle" },
    { value: "politics", text: "Politics" },
    { value: "science", text: "Science" },
    { value: "sports", text: "Sports" },
    { value: "technology", text: "Technology" },
    { value: "top", text: "Top" },
    { value: "tourism", text: "Tourism" },
    { value: "world", text: "World" },
    { value: "other", text: "Other" },
  ];
  
  export const categoryLabelMap = {
    business: "Business",
    crime: "Crime",
    domestic: "Domestic",
    education: "Education",
    entertainment: "Entertainment",
    environment: "Environment",
    food: "Food",
    health: "Health",
    lifestyle: "Lifestyle",
    politics: "Politics",
    science: "Science",
    sports: "Sports",
    technology: "Technology",
    top: "Top",
    tourism: "Tourism",
    world: "World",
    other: "Other",
  };
  
  export const availableTags = [
    { value: "accidents", text: "Accidents" },
    { value: "agriculture_and_farming", text: "Agriculture and Farming" },
    { value: "american_football", text: "American Football" },
    { value: "art_and_culture", text: "Art and Culture" },
    { value: "artificial_intelligence", text: "Artificial Intelligence" },
    { value: "automotive", text: "Automotive" },
    { value: "aviation", text: "Aviation" },
    { value: "awards_and_recognitions", text: "Awards and Recognitions" },
    { value: "banking_and_finance", text: "Banking and Finance" },
    { value: "baseball", text: "Baseball" },
    { value: "basketball", text: "Basketball" },
    { value: "boxing", text: "Boxing" },
    { value: "celebrity", text: "Celebrity" },
    { value: "chemicals", text: "Chemicals" },
    { value: "climate_and_weather", text: "Climate and Weather" },
    { value: "conflicts_war", text: "Conflicts & War" },
    { value: "corporate_news", text: "Corporate News" },
    { value: "corporate_social_responsibility", text: "Corporate Social Responsibility" },
    { value: "cricket", text: "Cricket" },
    { value: "crime", text: "Crime" },
    { value: "cryptocurrencies", text: "Cryptocurrencies" },
    { value: "cybercrime_and_cybersecurity", text: "Cybercrime and Cybersecurity" },
    { value: "diseases", text: "Diseases" },
    { value: "ecommerce", text: "E-commerce" },
    { value: "ecoriendly", text: "Eco-friendly" },
    { value: "economy", text: "Economy" },
    { value: "education", text: "Education" },
    { value: "elections", text: "elections" },
    { value: "energy", text: "Energy" },
    { value: "entertainment", text: "Entertainment" },
    { value: "fmcg", text: "FMCG" },
    { value: "fashion_and_lifestyle", text: "Fashion and Lifestyle" },
    { value: "field_hockey", text: "Field Hockey" },
    { value: "financial_markets", text: "Financial Markets" },
    { value: "food", text: "Food" },
    { value: "gaming", text: "Gaming" },
    { value: "golf", text: "Golf" },
    { value: "government", text: "Government" },
    { value: "gymnastics", text: "Gymnastics" },
    { value: "health_and_fitness", text: "Health and Fitness" },
    { value: "home_and_interior_design", text: "Home and Interior Design" },
    { value: "human_rights", text: "Human Rights" },
    { value: "immigration_and_migrant_issues", text: "Immigration and Migrant Issues" },
    { value: "insurance", text: "Insurance" },
    { value: "international_trade", text: "International Trade" },
    { value: "lgbtq", text: "LGBTQ" },
    { value: "law_and_justice", text: "Law and Justice" },
    { value: "mental_health", text: "Mental Health" },
    { value: "metal_mining", text: "Metal Mining" },
    { value: "mixed_martial_arts", text: "Mixed Martial Arts" },
    { value: "motorsports", text: "Motosports" },
    { value: "movies", text: "Movies" },
    { value: "national_security", text: "National Security" },
    { value: "natural_disasters", text: "Natural Disasters" },
    { value: "nonprofit_organizations", text: "Nonprofit Organizations" },
    { value: "ocean_conservation", text: "Ocean Conservation" },
    { value: "pharma_and_healthcare", text: "Pharma and Healthcare" },
    { value: "philanthropy", text: "Philantropy" },
    { value: "politics", text: "Politics" },
    { value: "pollution", text: "Pollution" },
    { value: "real_estate", text: "Real Estate" },
    { value: "recycling", text: "Recycling" },
    { value: "religion", text: "Religion" },
    { value: "religious_events_and_festivals", text: "Religious Events and Festivals" },
    { value: "renewable_energy", text: "Renewable Energy" },
    { value: "research", text: "Research" },
    { value: "rugby", text: "Rugby" },
    { value: "science_and_innovations", text: "Science and Innovations" },
    { value: "soccer", text: "Soccer" },
    { value: "social_media_and_internet", text: "Social Media and Internet" },
    { value: "space", text: "Space" },
    { value: "sports", text: "Sports" },
    { value: "startups_entrepreneurship", text: "Startups Entrepreneurship" },
    { value: "supply_chain_and_logistics", text: "Supply Chain and Logistics" },
    { value: "technology", text: "Technology" },
    { value: "telecom", text: "Telecom" },
    { value: "television", text: "Television" },
    { value: "tennis", text: "Tennis" },
    { value: "terrorism", text: "Terrorism" },
    { value: "textile", text: "Textile" },
    { value: "tourism", text: "Tourism" },
    { value: "volleyball", text: "Volleyball" },
    { value: "wildlife", text: "Wildlife" },
    { value: "worklife_balance", text: "Worklife Balance" },
    { value: "wrestling", text: "Wrestling" },
  ];
  
  export const tagLabelMap = {
    accidents: "Accidents",
    agriculture_and_farming: "Agriculture and Farming",
    american_football: "American Football",
    art_and_culture: "Art and Culture",
    artificial_intelligence: "Artificial Intelligence",
    automotive: "Automotive",
    aviation: "Aviation",
    awards_and_recognitions: "Awards and Recognitions",
    banking_and_finance: "Banking and Finance",
    baseball: "Baseball",
    basketball: "Basketball",
    boxing: "Boxing",
    celebrity: "Celebrity",
    chemicals: "Chemicals",
    climate_and_weather: "Climate and Weather",
    conflicts_war: "Conflicts & War",
    corporate_news: "Corporate News",
    corporate_social_responsibility: "Corporate Social Responsibility",
    cricket: "Cricket",
    crime: "Crime",
    cryptocurrencies: "Cryptocurrencies",
    cybercrime_and_cybersecurity: "Cybercrime and Cybersecurity",
    diseases: "Diseases",
    ecommerce: "E-commerce",
    ecoriendly: "Eco-friendly",
    economy: "Economy",
    education: "Education",
    elections: "elections",
    energy: "Energy",
    entertainment: "Entertainment",
    fmcg: "FMCG",
    fashion_and_lifestyle: "Fashion and Lifestyle",
    field_hockey: "Field Hockey",
    financial_markets: "Financial Markets",
    food: "Food",
    gaming: "Gaming",
    golf: "Golf",
    government: "Government",
    gymnastics: "Gymnastics",
    health_and_fitness: "Health and Fitness",
    home_and_interior_design: "Home and Interior Design",
    human_rights: "Human Rights",
    immigration_and_migrant_issues: "Immigration and Migrant Issues",
    insurance: "Insurance",
    international_trade: "International Trade",
    lgbtq: "LGBTQ",
    law_and_justice: "Law and Justice",
    mental_health: "Mental Health",
    metal_mining: "Metal Mining",
    mixed_martial_arts: "Mixed Martial Arts",
    motorsports: "Motosports",
    movies: "Movies",
    national_security: "National Security",
    natural_disasters: "Natural Disasters",
    nonprofit_organizations: "Nonprofit Organizations",
    ocean_conservation: "Ocean Conservation",
    pharma_and_healthcare: "Pharma and Healthcare",
    philanthropy: "Philantropy",
    politics: "Politics",
    pollution: "Pollution",
    real_estate: "Real Estate",
    recycling: "Recycling",
    religion: "Religion",
    religious_events_and_festivals: "Religious Events and Festivals",
    renewable_energy: "Renewable Energy",
    research: "Research",
    rugby: "Rugby",
    science_and_innovations: "Science and Innovations",
    soccer: "Soccer",
    social_media_and_internet: "Social Media and Internet",
    space: "Space",
    sports: "Sports",
    startups_entrepreneurship: "Startups Entrepreneurship",
    supply_chain_and_logistics: "Supply Chain and Logistics",
    technology: "Technology",
    telecom: "Telecom",
    television: "Television",
    tennis: "Tennis",
    terrorism: "Terrorism",
    textile: "Textile",
    tourism: "Tourism",
    volleyball: "Volleyball",
    wildlife: "Wildlife",
    worklife_balance: "Worklife Balance",
    wrestling: "Wrestling",
  };
  